# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
