# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20170515_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_cover',
            field=models.ImageField(upload_to='images/covers'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_thumbnail',
            field=models.ImageField(upload_to='images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type_id',
            field=models.IntegerField(choices=[(1, 'Restaurant'), (2, 'Bar'), (3, 'Bar and Restaurant')], default=1),
        ),
    ]
