# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20170519_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image_thumbnail',
            field=models.ImageField(upload_to='images/thumbnails'),
        ),
    ]
