# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20170605_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('facebook_id', models.CharField(max_length=200)),
                ('profile_picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='subscribers',
            field=models.ManyToManyField(through='places.PlaceSubscriber', to='places.AppUser'),
        ),
    ]
