# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20170730_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesubscriber',
            name='date_subscribed',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
